### ISSUE TITLE
JAMstack : A Complete Beginner's Guide

### ISSUE THREAD

**Issue by pineapple-content** [stackbit/jamstack-wtf#6]
This post is a great tutorial for beginner's looking to understand what Jamstack is. It covers the history and foundations of JAMstack and explains the architecture. It includes a comparison of the traditional workflow vs Jamstack workflow and highlights the advantages of using Jamstack for developrs. It also provides a step-by-step guide on how to build a website using JAMstack using a real-time example for readers to use as a reference. 
https://buttercms.com/blog/what-is-jamstack

**Comment by peduarte** [comment]
Awesome, thanks for that!

**Comment by TomasBankauskas** [comment]
@pineapple-content thank you, added to the site.
